
enum  SocketEvent {
    SEND_DOCUMENT_CHANGES = "SEND_DOCUMENT_CHANGES",
    RECEIVE_DOCUMENT_CHANGES = "RECEIVE_DOCUMENT_CHANGES",
    CURRENT_USERS = "CURRENT_USERS",
    USER_DISCONNECT_FROM_CURRENT_USERS = "USER_DISCONNECT_FROM_CURRENT_USERS",
    UPDATE_TITLE = "UPDATE_TITLE"
}

export { SocketEvent};